version: 2.0.{build}.0

os: Visual Studio 2017

environment:
  CoverallsRepoToken:
    secure: t/5ID5XZAyFKZNmgVJIrcs2Ah7Bn1Kr2cmAZcmEbvl/lGHHl6F4sxSLHK89z7I7E

build:
  project: src\SqlLocalDb.msbuild
  verbosity: minimal

artifacts:
  - path: src\BuildOutput\*.nupkg
  - path: src\BuildOutput\*.zip
  - path: src\TestResults\*\*.coverage

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off

deploy:

  - provider: GitHub
    tag: "$(APPVEYOR_REPO_TAG_NAME)"
    release: "SQL LocalDB Wrapper $(APPVEYOR_REPO_TAG_NAME)"
    description: "$(GitHubReleaseDescription)"
    auth_token:
      secure: h9fLtmesz0AoFVrhv2oYqGvBQnwY7+Io0uASRjts8yFv5dUzks/go0BpVpUeM9tA
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true

  - provider: NuGet
    api_key:
      secure: OKbODD04RIoauopeXve4FsbtYb6wreSRms0k3SnH7b/Gj/6cQhVQHhu2xMjoSlQc
    artifact: /.*\.nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true
