os: Visual Studio 2017
version: 2.0.0.{build}

environment:
  CLI_VERSION: 1.0.1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

assembly_info:
  patch: true
  file: AssemblyVersion.cs
  assembly_version: "3.0.0.0"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyVersion.cs
  assembly_version: "2.0.0.0"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build_script:
  - ps: .\Build.ps1

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\System.Data.SqlLocalDb.TestApp.*

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off

deploy:

  - provider: NuGet
    api_key:
      secure: OKbODD04RIoauopeXve4FsbtYb6wreSRms0k3SnH7b/Gj/6cQhVQHhu2xMjoSlQc
    artifact: /.*\.nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true
